server:
    port: 9000

spring:
  datasource:
    name: auth-server
    generate-unique-name: false
    
management:
  endpoints:
    web:
      exposure:
        include: '*'

logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.springframework.security: INFO
    org.springframework.security.oauth2: INFO